### PR TITLE
Fixed error message for connection exceptions

### PR DESCRIPTION
**Pull request by Elnadrion**
Hi there!

There is only handling of Guzzle RequestExceptions. When my team and I got another type of exception - package drives us crazy with it's message 😅 I've changed this behavior, and turn this:

image

into this:

image

### CODE REVIEW

**Comment by Elnadrion** [comment]
@tPl0ch could you please check this PR?

**Comment by Elnadrion** [comment]
Omg I have this tests failed in master branch 😅

**Comment by Elnadrion** [comment]
@tPl0ch looks like you have incorrect tag in `avro-php` lib
Look:
https://github.com/flix-tech/avro-php/blob/4.2.0/lib/avro/schema.php#L392
https://github.com/flix-tech/avro-php/blob/master/lib/avro/schema.php#L392

Latest fix from master branch solves this tests

**Comment by tPl0ch** [comment]
@Elnadrion can you merge the latest changes into your branch?

**Comment by Elnadrion** [comment]
I~~'m watching you~~ subscribed to this repository :)

**Comment by Elnadrion** [comment]
I haven't pulled new CI checks though. 1 sec

**Comment by tPl0ch** [comment]
Released as https://github.com/flix-tech/schema-registry-php-client/releases/tag/7.6.0

**Pull request merged**
